src/app/__init__.py
from flask import Flask, render_template
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

limiter = Limiter(
    key_func=get_remote_address,
    default_limits=["2 per second", "86400 per day"],
    storage_uri="memory://",
)


@limiter.request_filter
def ip_whitelist():
    """Add some exemptions to the limiter."""
    from flask import request

    return request.remote_addr in ("127.0.0.1", "localhost")


def create_app(config_file: str = "config.py"):
    """App factory."""
    app = Flask(__name__)

    if config_file:
        app.config.from_pyfile(config_file)

    from . import routes

    limiter.init_app(app)
    app.register_blueprint(routes.bp)

    return app

src/app/routes.py
"""Routes for the app."""
from flask import Blueprint, jsonify, render_template, request

from . import querying
from .plotting import make_bar_chart

bp = Blueprint("routes", __name__)


@bp.route("/")
def search_form():
    """Present the search form for the user."""
    query = request.args.get("q", None)
    if query is None or not query:
        return render_template("search.html")

    result = querying.count_lines(query)
    chart = make_bar_chart(result["overall"])

    return render_template(
        "search.html",
        search_results=result,
        query=query,
        chart=chart,
    )


@bp.route("/health")
def health():
    """Health check endpoint."""
    return "ok"

src/app/templates/base.html
<!doctype html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    <script src="https://cdn.plot.ly/plotly-1.2.0.min.js"></script>
</head>

<body>
    <h1>Friends Oh My God!</h1>
    <div>
        <p>
            We were rewatching some old Friends episodes at home when I took notice that the phrase <i>"oh my god"</i>
            comes up a lot in that show. As any reasonable person would, I compiled script data and built a website to
            prove my point.
        </p>

        <p>
            This webapp lets you check how often phrases like <a href='/?q=oh+my+god'>"oh my god"</a> are said in
            Friends, Seinfeld, and Sex and the City. You can use the search bar below to compute the frequency of any
            phrase you'd like.
        </p>
    </div>

    <hr>
    <form action="{{url_for('routes.search_form')}}" method="get">
        <div class="form-group">
            <input type="text" class="form-control" id="q" name='q' placeholder="Any phrase you want!">

        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>

    {% block content %}{% endblock %}

    <hr>
    <button class="btn btn btn-outline-dark btn-block" type="button" data-toggle="collapse" data-target="#info"
        aria-expanded="false" aria-controls="collapseExample">
        Click me if you'd like to read more about this app!
    </button>

    <div class="collapse" id=info>
        <hr>
        <p>I had some help putting these data together!</p>
        <p>
            Shout out to <a href='https://github.com/colinpollock/seinfeld-scripts'>Colin Pollock</a> for the
            <i>excellent</i> Seinfeld dataset &#129305; . Shout out to <a
                href='https://quotennial.github.io/Friends-engineering/'>Yusuf Sohoye</a> for the regex to parse through
            Friends script files &#129304; . I stole the Sex and the City data from <a
                href='https://www.kaggle.com/snapcrack/every-sex-and-the-city-script'>Kaggle</a> and will <i>not</i> be
            giving shout outs because there was still a lot of cleaning work to do there.
        </p>

        <p>
            You can download the full (gzipped) SQLite3 database <a
                href='http://nolanc.heliohost.org/omg-data/data.db.gz'>here</a>
            (it's not very large) &#128540; .
        </p>
    </div>

    <style>
        body {
            max-width: 1000px;
            padding: 2em;
        }

    </style>
</body>

src/app/templates/search.html
{% extends 'base.html' %}
{% block content %}


{% if search_results is defined %}
<hr>
<h2>Proportion of lines containing "<code>{{query | safe}}</code>"</h2>

<div id=chart_container></div>
<script>
    var chart = JSON.parse('{{ chart | tojson | safe }}');
    var d3 = Plotly.d3;
    var gd3 = d3.select('#chart_container').append('div').style({
        width: '100%',
        height: '300px',
    });

    var gd = gd3.node();
    var plot = Plotly.newPlot(gd, chart.data, chart.layout, chart.config);
    function resize() { Plotly.Plots.resize(gd) };

    window.onresize = resize
    resize()

</script>



<p>
    *Those error bars are a 95&#37; confidence interval computed via <a
        href='https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval#Normal_approximation_interval'>normal
        approximation</a>.
</p>

<hr>

<!-- TABLES FOR THE EXACT -->
<button class="btn btn btn-outline-dark btn-block" type="button" data-toggle="collapse" data-target="#tables"
    aria-expanded="false" aria-controls="collapseExample">
    Data tables are a click away!
</button>

<div class="collapse" id=tables>
    <hr>

    <div class=overall_table>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Show</th>
                    <th scope="col">Total Lines</th>
                    <th scope="col">Lines including "<code>{{query | safe}}</code>"</th>
                    <th scope="col">Probability of "<code>{{query | safe}}</code>"</th>
                </tr>
            </thead>
            <tbody>
                {% for show, data in search_results['overall'].items() %}
                <tr>
                    <td>{{show | title}}</td>
                    <td>{{data['n']}}</td>
                    <td>{{data['k']}}</td>
                    <td>{{(data['p'] * 100) | round(3)}}%</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <h3>By Character</h3>
    <hr>
    {% for show, characters in search_results['by_character'].items() %} <div class=show_character_table>
        <h4>{{show | title}}</h4>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Character</th>
                    <th scope="col">Total Lines</th>
                    <th scope="col">Lines including "<code>{{query | safe}}</code>"</th>
                    <th scope="col">Probability of "<code>{{query | safe}}</code>"</th>
                </tr>
            </thead>
            <tbody>
                {% for character in characters %}
                <tr>
                    <td>{{character['character_name'] | title}}</td>
                    <td>{{character['n']}}</td>
                    <td>{{character['k']}}</td>
                    <td>{{(character['p'] * 100) | round(3)}}%</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endfor %}
</div>
{% endif %} {% endblock %}